// GENERATED by scripts/sync-targets.mjs from ocp-targets.json — do not edit.
// OpenShift 4.21 shares 'react-router-dom-v5-compat'.
export { Link, useSearchParams } from 'react-router-dom-v5-compat';
